-- Auto-generated by Claude from football wiki data
-- Season: 01-2025-26 (Juniores Ardor Bollate)
-- Tables with no available data for this season are omitted
-- (player_attributes, player_injuries, sessions, session_exercises,
-- session_attendance, match_assists, match_lineups, match_cards,
-- formations, season_objectives, exercises)

-- seasons
DELETE FROM seasons WHERE code = '01-2025-26';
INSERT INTO seasons (code, name, category, competition, girone, delegazione, year_start, year_end, piazzamento) VALUES
('01-2025-26', 'Ardor Bollate Juniores 2025-26', 'Juniores', 'Juniores Provinciali U19', 'B', 'Milano', 2025, 2026, '2° posto campionato (22V 2P 2S, 93-31); 1° posto Coppa Lombardia U19 — Campioni');

-- players
DELETE FROM players WHERE season_code = '01-2025-26';
INSERT INTO players (id, season_code, nome, cognome, anno_nascita, ruolo, fuoriquota, note) VALUES
('mattia-annoni', '01-2025-26', 'Mattia', 'Annoni', 2007, 'attaccante', false, 'Centravanti boa, rincalzo.'),
('paolo-banfi', '01-2025-26', 'Paolo', 'Banfi', 2007, 'attaccante', false, 'Numero 10, fantasista, giocatore chiave.'),
('luca-belotti', '01-2025-26', 'Luca', 'Belotti', 2007, 'portiere', false, 'Secondo portiere, bravo coi piedi.'),
('alessandro-boniardi', '01-2025-26', 'Alessandro', 'Boniardi', 2008, 'attaccante', false, 'Attaccante centrale/esterno, forte nel tiro.'),
('edoardo-boniardi', '01-2025-26', 'Edoardo', 'Boniardi', 2008, 'difensore', false, 'Centrale/terzino aggressivo; rientrato a dicembre da infortunio.'),
('lorenzo-brana', '01-2025-26', 'Lorenzo', 'Brana', 2008, 'difensore', false, 'Centrale ruvido; infortunato quasi tutta la stagione, rientrato a marzo.'),
('federico-celardo', '01-2025-26', 'Federico', 'Celardo', 2006, NULL, true, 'Non in rosa, viene solo ad allenarsi.'),
('christian-cimmino', '01-2025-26', 'Christian', 'Cimmino', 2006, 'centrocampista', true, 'Capitano; infortunato tutto l''anno.'),
('gabriele-columpsi', '01-2025-26', 'Gabriele', 'Columpsi', 2008, 'attaccante', false, 'Fisico devastante; vari infortuni, decisivo in coppa col Vigevano poi stop stagione.'),
('alessandro-cuzmin', '01-2025-26', 'Alessandro', 'Cuzmin', 2008, 'difensore', false, 'Centrale/terzino, qualità altalenanti, 3 esclusioni disciplinari.'),
('diego-favaron', '01-2025-26', 'Diego', 'Favaron', 2007, 'difensore', false, 'Terzino sinistro, cresciuto molto durante l''anno.'),
('mattia-favaron', '01-2025-26', 'Mattia', 'Favaron', 2006, 'centrocampista', true, 'Centrocampista centrale, bravo nei passaggi e sui calci da fermo.'),
('mattia-ghioni', '01-2025-26', 'Mattia', 'Ghioni', 2006, 'difensore', true, 'Terzino, uomo spogliatoio, qualche minuto giocato.'),
('federico-iannace', '01-2025-26', 'Federico', 'Iannace', 2008, 'attaccante', false, 'Esterno offensivo tecnico, fatica dopo un infortunio.'),
('federico-irmici', '01-2025-26', 'Federico', 'Irmici', 2007, NULL, false, 'Non in rosa, viene solo ad allenarsi.'),
('alessandro-lapiciriella', '01-2025-26', 'Alessandro', 'Lapiciriella', 2008, 'centrocampista', false, 'Centrocampista basso ma tecnico; perso fiducia con poco spazio.'),
('riccardo-lasagna', '01-2025-26', 'Riccardo', 'Lasagna', 2007, 'centrocampista', false, 'Capitano, playmaker.'),
('luca-lovalvo', '01-2025-26', 'Luca', 'Lovalvo', 2007, 'centrocampista', false, 'Centrocampista, cresciuto molto durante l''anno (anche ''Lo Valvo'').'),
('gabriele-mingrone', '01-2025-26', 'Gabriele', 'Mingrone', 2008, 'attaccante', false, 'Mezzapunta/attaccante, capocannoniere, giocatore chiave.'),
('tommaso-minora', '01-2025-26', 'Tommaso', 'Minora', 2007, 'difensore', false, 'Centrale alto e forte di testa, sempre presente.'),
('gabriele-pagliato', '01-2025-26', 'Gabriele', 'Pagliato', 2007, 'difensore', false, 'Terzino destro ''Pitbull'', fisico devastante.'),
('marco-palmisano', '01-2025-26', 'Marco', 'Palmisano', 2008, 'portiere', false, 'Portiere titolare, para rigori.'),
('nicolo-parolini', '01-2025-26', 'Nicolo', 'Parolini', 2007, 'difensore', false, 'Centrale, annata eccezionale.'),
('samuele-pedulla', '01-2025-26', 'Samuele', 'Pedulla', 2008, 'difensore', false, 'Centrale/terzino, fuori dalle rotazioni principali.'),
('riccardo-picca', '01-2025-26', 'Riccardo', 'Picca', 2007, 'centrocampista', false, 'Centrocampista fisico e tecnico; infortunio nel finale di stagione.'),
('mattia-portararo', '01-2025-26', 'Mattia', 'Portararo', 2007, 'centrocampista', false, 'Esterno/terzino; rottura del crociato a inizio stagione, stagione finita.'),
('alessandro-riccio', '01-2025-26', 'Alessandro', 'Riccio', 2008, 'difensore', false, 'Terzino, migliorato molto durante l''anno.'),
('francesco-taronna', '01-2025-26', 'Francesco', 'Taronna', 2008, 'centrocampista', false, 'Mediano, titolare inamovibile a fine stagione.'),
('antonio-mingrone', '01-2025-26', 'Antonio', 'Mingrone', 2005, 'attaccante', true, 'Attaccante prima squadra, chiamato per le partite importanti.'),
('riccardo-conti', '01-2025-26', 'Riccardo', 'Conti', 2005, 'difensore', true, 'Terzino, chiamato solo a fine stagione.'),
('mattia-montagner', '01-2025-26', 'Mattia', 'Montagner', 2005, 'centrocampista', true, 'Quinto di centrocampo, decisivo in coppa (doppietta in semifinale andata).'),
('riccardo-boniardi', '01-2025-26', 'Riccardo', 'Boniardi', 2005, 'difensore', true, 'Centrale, chiamato solo a fine stagione, fratello di Edoardo.'),
('andrea-cesaratto', '01-2025-26', 'Andrea', 'Cesaratto', 2005, 'difensore', true, 'Centrale/terzino sx, regista basso da metà stagione, gol decisivo in coppa.'),
('mattia-cascio', '01-2025-26', 'Mattia', 'Cascio', 2005, 'attaccante', true, 'Esterno veloce, sempre a disposizione.');

-- player_stats
DELETE FROM player_stats WHERE season_code = '01-2025-26';
INSERT INTO player_stats (player_id, season_code, presenze_allenamenti, totale_allenamenti, presenze_partite, minuti_giocati, gol, assist) VALUES
('mattia-annoni', '01-2025-26', NULL, NULL, NULL, NULL, 2, NULL),
('paolo-banfi', '01-2025-26', NULL, NULL, NULL, NULL, 17, NULL),
('luca-belotti', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('alessandro-boniardi', '01-2025-26', NULL, NULL, NULL, NULL, 23, NULL),
('edoardo-boniardi', '01-2025-26', NULL, NULL, NULL, NULL, 1, NULL),
('lorenzo-brana', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('federico-celardo', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('christian-cimmino', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('gabriele-columpsi', '01-2025-26', NULL, NULL, NULL, NULL, 8, NULL),
('alessandro-cuzmin', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('diego-favaron', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('mattia-favaron', '01-2025-26', NULL, NULL, NULL, NULL, 1, NULL),
('mattia-ghioni', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('federico-iannace', '01-2025-26', NULL, NULL, NULL, NULL, 1, NULL),
('federico-irmici', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('alessandro-lapiciriella', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('riccardo-lasagna', '01-2025-26', NULL, NULL, NULL, NULL, 1, NULL),
('luca-lovalvo', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('gabriele-mingrone', '01-2025-26', NULL, NULL, NULL, NULL, 31, NULL),
('tommaso-minora', '01-2025-26', NULL, NULL, NULL, NULL, 1, NULL),
('gabriele-pagliato', '01-2025-26', NULL, NULL, NULL, NULL, 6, NULL),
('marco-palmisano', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('nicolo-parolini', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('samuele-pedulla', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('riccardo-picca', '01-2025-26', NULL, NULL, NULL, NULL, 10, NULL),
('mattia-portararo', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('alessandro-riccio', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('francesco-taronna', '01-2025-26', NULL, NULL, NULL, NULL, 3, NULL),
('antonio-mingrone', '01-2025-26', NULL, NULL, NULL, NULL, 5, NULL),
('riccardo-conti', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('mattia-montagner', '01-2025-26', NULL, NULL, NULL, NULL, 2, NULL),
('riccardo-boniardi', '01-2025-26', NULL, NULL, NULL, NULL, 0, NULL),
('andrea-cesaratto', '01-2025-26', NULL, NULL, NULL, NULL, 1, NULL),
('mattia-cascio', '01-2025-26', NULL, NULL, NULL, NULL, 1, NULL);

-- matches
DELETE FROM match_scorers WHERE match_id IN (SELECT id FROM matches WHERE season_code = '01-2025-26');
DELETE FROM matches WHERE season_code = '01-2025-26';
INSERT INTO matches (id, season_code, data, avversario, competizione, fase, casa_trasferta, gol_fatti, gol_subiti, status, note) VALUES
('20251004-vs-polisportiva-or-pa-s', '01-2025-26', '2025-10-04', 'Polisportiva Or. Pa. S.', 'campionato', NULL, 'trasferta', 5, 2, 'played', NULL),
('20251011-vs-calcio-bonola', '01-2025-26', '2025-10-11', 'Calcio Bonola', 'campionato', NULL, 'casa', 3, 1, 'played', NULL),
('20251018-vs-cassina-nuova', '01-2025-26', '2025-10-18', 'Cassina Nuova', 'campionato', NULL, 'casa', 4, 0, 'played', NULL),
('20251025-vs-bollatese', '01-2025-26', '2025-10-25', 'Bollatese', 'campionato', NULL, 'trasferta', 6, 0, 'played', NULL),
('20251101-vs-cob-91', '01-2025-26', '2025-11-01', 'Cob 91', 'campionato', NULL, 'casa', 5, 3, 'played', NULL),
('20251108-vs-vigor-fc', '01-2025-26', '2025-11-08', 'Vigor FC', 'campionato', NULL, 'trasferta', 2, 3, 'played', NULL),
('20251115-vs-seguro', '01-2025-26', '2025-11-15', 'Seguro', 'campionato', NULL, 'casa', 6, 2, 'played', NULL),
('20251122-vs-vighignolo', '01-2025-26', '2025-11-22', 'Vighignolo', 'campionato', NULL, 'trasferta', 2, 1, 'played', NULL),
('20251129-vs-garibaldina-1932', '01-2025-26', '2025-11-29', 'Garibaldina 1932', 'campionato', NULL, 'casa', 5, 2, 'played', NULL),
('20251206-vs-villapizzone', '01-2025-26', '2025-12-06', 'Villapizzone', 'campionato', NULL, 'trasferta', 2, 2, 'played', NULL),
('20251213-vs-quinto-romano', '01-2025-26', '2025-12-13', 'Quinto Romano', 'campionato', NULL, 'casa', 5, 0, 'played', NULL),
('20251220-vs-sempione-half-1919', '01-2025-26', '2025-12-20', 'Sempione Half 1919', 'campionato', NULL, 'trasferta', 5, 0, 'played', NULL),
('20260110-vs-pro-novate', '01-2025-26', '2026-01-10', 'Pro Novate', 'campionato', NULL, 'casa', 4, 1, 'played', NULL),
('20260117-vs-polisportiva-or-pa-s', '01-2025-26', '2026-01-17', 'Polisportiva Or. Pa. S.', 'campionato', NULL, 'casa', 2, 1, 'played', NULL),
('20260124-vs-calcio-bonola', '01-2025-26', '2026-01-24', 'Calcio Bonola', 'campionato', NULL, 'trasferta', 2, 1, 'played', NULL),
('20260131-vs-cassina-nuova', '01-2025-26', '2026-01-31', 'Cassina Nuova', 'campionato', NULL, 'trasferta', 6, 2, 'played', NULL),
('20260207-vs-bollatese', '01-2025-26', '2026-02-07', 'Bollatese', 'campionato', NULL, 'casa', 7, 1, 'played', NULL),
('20260214-vs-cob-91', '01-2025-26', '2026-02-14', 'Cob 91', 'campionato', NULL, 'trasferta', 3, 0, 'played', NULL),
('20260221-vs-vigor-fc', '01-2025-26', '2026-02-21', 'Vigor FC', 'campionato', NULL, 'casa', 1, 2, 'played', NULL),
('20260228-vs-seguro', '01-2025-26', '2026-02-28', 'Seguro', 'campionato', NULL, 'trasferta', 3, 0, 'played', NULL),
('20260307-vs-vighignolo', '01-2025-26', '2026-03-07', 'Vighignolo', 'campionato', NULL, 'casa', 2, 1, 'played', NULL),
('20260314-vs-garibaldina-1932', '01-2025-26', '2026-03-14', 'Garibaldina 1932', 'campionato', NULL, 'trasferta', 1, 0, 'played', NULL),
('20260321-vs-villapizzone', '01-2025-26', '2026-03-21', 'Villapizzone', 'campionato', NULL, 'casa', 3, 2, 'played', NULL),
('20260328-vs-quinto-romano', '01-2025-26', '2026-03-28', 'Quinto Romano', 'campionato', NULL, 'trasferta', 3, 1, 'played', NULL),
('20260404-vs-sempione-half-1919', '01-2025-26', '2026-04-04', 'Sempione Half 1919', 'campionato', NULL, 'casa', 3, 3, 'played', NULL),
('20260411-vs-pro-novate', '01-2025-26', '2026-04-11', 'Pro Novate', 'campionato', NULL, 'trasferta', 3, 0, 'played', NULL),
('20250913-vs-cassina-nuova', '01-2025-26', '2025-09-13', 'Cassina Nuova', 'coppa-lombardia', 'girone', 'casa', 4, 2, 'played', NULL),
('20250923-vs-pro-novate', '01-2025-26', '2025-09-23', 'Pro Novate', 'coppa-lombardia', 'girone', 'trasferta', 3, 1, 'played', NULL),
('20251028-vs-vighi-1967', '01-2025-26', '2025-10-28', 'Vighi 1967', 'coppa-lombardia', 'trentaduesimi', 'casa', 4, 2, 'played', NULL),
('20251118-vs-centro-giov-boffalorese', '01-2025-26', '2025-11-18', 'Centro Giov. Boffalorese', 'coppa-lombardia', 'sedicesimi', 'trasferta', 6, 2, 'played', NULL),
('20260205-vs-vigevano-calcio', '01-2025-26', '2026-02-05', 'Vigevano Calcio', 'coppa-lombardia', 'ottavi', 'casa', 2, 1, 'played', 'Columpsi decisivo, infortunato nel finale'),
('20260303-vs-tradate-abbiate', '01-2025-26', '2026-03-03', 'Tradate Abbiate', 'coppa-lombardia', 'quarti', 'casa', 3, 1, 'played', NULL),
('20260408-vs-vigor-fc', '01-2025-26', '2026-04-08', 'Vigor FC', 'coppa-lombardia', 'semifinale', 'casa', 3, 2, 'played', 'Doppietta Montagner M., gol Mingrone A.'),
('20260420-vs-vigor-fc', '01-2025-26', '2026-04-20', 'Vigor FC', 'coppa-lombardia', 'semifinale', 'trasferta', 2, 3, 'played', 'Qualificazione ai rigori (4-2)'),
('20260503-vs-vidalengo', '01-2025-26', '2026-05-03', 'Vidalengo', 'coppa-lombardia', 'finale', 'casa', 1, 0, 'played', 'Campioni di Coppa Lombardia! Rigore decisivo Mingrone G.');

-- opponents
DELETE FROM opponents WHERE season_code = '01-2025-26';
INSERT INTO opponents (season_code, nome, gol_fatti, gol_subiti, note) VALUES
('01-2025-26', 'Polisportiva Or. Pa. S.', 7, 3, NULL),
('01-2025-26', 'Calcio Bonola', 5, 2, NULL),
('01-2025-26', 'Cassina Nuova', 14, 4, NULL),
('01-2025-26', 'Bollatese', 13, 1, NULL),
('01-2025-26', 'Cob 91', 8, 3, NULL),
('01-2025-26', 'Vigor FC', 8, 10, '1ª in classifica, unica squadra imbattuta del girone (le uniche due sconfitte stagionali subite proprio contro l''Ardor); eliminata in semifinale di Coppa Lombardia ai rigori (4-2).'),
('01-2025-26', 'Seguro', 9, 2, NULL),
('01-2025-26', 'Vighignolo', 4, 2, NULL),
('01-2025-26', 'Garibaldina 1932', 6, 2, NULL),
('01-2025-26', 'Villapizzone', 5, 4, 'Pareggio all''andata (2-2).'),
('01-2025-26', 'Quinto Romano', 8, 1, NULL),
('01-2025-26', 'Sempione Half 1919', 8, 3, 'Pareggio al ritorno (3-3).'),
('01-2025-26', 'Pro Novate', 10, 2, NULL),
('01-2025-26', 'Vighi 1967', 4, 2, NULL),
('01-2025-26', 'Centro Giov. Boffalorese', 6, 2, NULL),
('01-2025-26', 'Vigevano Calcio', 2, 1, 'Ottavi di Coppa Lombardia: Columpsi decisivo al rientro dagli infortuni, ma si infortuna nel finale e chiude la stagione.'),
('01-2025-26', 'Tradate Abbiate', 3, 1, NULL),
('01-2025-26', 'Vidalengo', 1, 0, 'Finale di Coppa Lombardia, vinta 1-0 grazie al rigore di Gabriele Mingrone — Campioni!');

